import React from 'react';
import { 
  Box, 
  Typography, 
  Paper, 
  Container, 
  Button, 
  Grid, 
  Card, 
  CardContent, 
  CardActions,
  Divider,
  LinearProgress
} from '@mui/material';
import { useAuth } from '../../phase1-auth/contexts/AuthContext';

export const Dashboard: React.FC = () => {
  const { user } = useAuth();
  
  return (
    <Container maxWidth="xl" sx={{ py: 4 }}>
      <Box sx={{ mb: 4 }}>
        <Typography variant="h4" gutterBottom>
          Project Dashboard
        </Typography>
        <Typography variant="subtitle1" color="text.secondary">
          Welcome back, {user?.displayName || 'User'}! This dashboard will be fully implemented in Phase 5.
        </Typography>
      </Box>
      
      <Grid container spacing={3}>
        {/* Project Overview Card */}
        <Grid item xs={12} md={8}>
          <Paper elevation={3} sx={{ p: 3, borderRadius: 2, height: '100%' }}>
            <Typography variant="h5" gutterBottom>
              Project Overview
            </Typography>
            <Divider sx={{ my: 2 }} />
            <Typography variant="body1" paragraph>
              This dashboard will provide a comprehensive view of your project's progress, milestones, and team performance.
            </Typography>
            <Box sx={{ mt: 3 }}>
              <Typography variant="subtitle2" gutterBottom>
                Overall Progress
              </Typography>
              <LinearProgress variant="determinate" value={30} sx={{ height: 10, borderRadius: 5 }} />
              <Typography variant="caption" sx={{ display: 'block', mt: 1 }}>
                30% Complete
              </Typography>
            </Box>
          </Paper>
        </Grid>
        
        {/* Connect Jira Card */}
        <Grid item xs={12} md={4}>
          <Paper elevation={3} sx={{ p: 3, borderRadius: 2, height: '100%' }}>
            <Typography variant="h5" gutterBottom>
              Jira Integration
            </Typography>
            <Divider sx={{ my: 2 }} />
            <Typography variant="body1" paragraph>
              Connect your Jira account to import tickets and track progress.
            </Typography>
            <Button 
              variant="contained" 
              color="primary" 
              fullWidth
              sx={{ mt: 2 }}
            >
              Connect Jira Account
            </Button>
          </Paper>
        </Grid>
        
        {/* Upcoming Milestones */}
        <Grid item xs={12}>
          <Typography variant="h5" gutterBottom sx={{ mt: 2 }}>
            Upcoming Milestones
          </Typography>
          <Grid container spacing={2}>
            {[1, 2, 3].map((item) => (
              <Grid item xs={12} md={4} key={item}>
                <Card elevation={2}>
                  <CardContent>
                    <Typography variant="h6" gutterBottom>
                      Milestone {item}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      This is a placeholder for milestone information that will be generated by the AI workflow system.
                    </Typography>
                    <Box sx={{ mt: 2 }}>
                      <Typography variant="caption" display="block">
                        Progress:
                      </Typography>
                      <LinearProgress 
                        variant="determinate" 
                        value={Math.floor(Math.random() * 100)} 
                        sx={{ height: 6, borderRadius: 3 }} 
                      />
                    </Box>
                  </CardContent>
                  <CardActions>
                    <Button size="small">View Details</Button>
                  </CardActions>
                </Card>
              </Grid>
            ))}
          </Grid>
        </Grid>
      </Grid>
      
      <Box sx={{ mt: 4, textAlign: 'center' }}>
        <Typography variant="body2" color="text.secondary">
          The full dashboard with AI-generated workflows, Jira integration, and analytics will be implemented in Phase 5.
        </Typography>
      </Box>
    </Container>
  );
}; 